# Wiliton Abreu Rodrigues 
# Edoras - cssc2301
# SDSU - CS570 (summer 20)
# REDid: 824508185

# A Makefile for Program 1, CS570

TARGET = mulproc

CC = gcc
CFLAGS = -g -std=c99

${TARGET}:	${TARGET}.o
		${CC} -o ${TARGET} ${TARGET}.o


clean:
		rm -f ${TARGET} ${TARGET}.o
